[package]
name = "bindings"
version = "0.1.0"
edition = "2021"

[features]
host = []

[dependencies]
wasmcb = { path="../wasmcb" }
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.128"
